create table `aap_form_input` (
    `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'form input id',
    `name` varchar(256) NOT NULL COMMENT 'form input name',
    `display` varchar(512) NOT NULL COMMENT 'the label of this input',
    `pname` varchar(128) NOT NULL COMMENT 'the parameter name of the input',
    `help_message` varchar(4096) NOT NULL DEFAULT '' COMMENT 'help message of the input',
    `assignedAttrs` text NOT NULL COMMENT 'additional attributes assigned by the user, a json string',
    `form_input_type` varchar(64) NOT NULL COMMENT 'type of the input',
    `detail` text NOT NULL COMMENT 'the detail configuration of this input, a json string',
    `op_user` varchar(128) NOT NULL DEFAULT 'UNKNOWN_USER' COMMENT 'user that last modifies this form input',
    `ctime` int(10) NOT NULL DEFAULT 0 COMMENT 'create timestamp',
    `mtime` int(10) NOT NULL DEFAULT 0 COMMENT 'last modify timestamp',
    `ext` varchar(1024) NOT NULL DEFAULT '' COMMENT 'for future use',
    PRIMARY KEY (`id`),
    INDEX `name` (`name`),
    INDEX `form_input_type` (`form_input_type`),
    INDEX `pname` (`pname`),
    INDEX `ctime` (`ctime`),
    INDEX `mtime` (`mtime`),
    INDEX `op_user` (`op_user`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'save form input records';
